FROM node:20 AS builder
WORKDIR /app
COPY ./frontend/package*.json ./
RUN npm install
COPY ./frontend .
ARG VITE_API_BASE
ENV VITE_API_BASE $VITE_API_BASE
RUN npm run build

FROM nginx:1.27
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf.template /etc/nginx/conf.d/nginx.conf.template
COPY --chmod=755 docker-entry-frontend.sh /
ENTRYPOINT ["sh", "/docker-entry-frontend.sh"]
CMD ["nginx", "-g", "daemon off;"]
