FROM golang:1.24.6 AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o backend main.go

FROM gcr.io/distroless/static-debian12
WORKDIR /app
COPY --from=builder /app/backend .
COPY .env .
COPY config.ini .

EXPOSE 8080
CMD ["./backend"]
