services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    expose:
      - "8080"
    networks:
      - internal

  frontend:
    build:
      context: ./frontend
      dockerfile: ../Dockerfile.frontend
      args:
        VITE_API_BASE: https://${DOMAIN_NAME}/api
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend
    networks:
      - internal
    restart: always

networks:
  internal:
    driver: bridge
