services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    expose:
      - "8080"
    networks:
      - internal

  frontend:
    build:
      context: ./frontend
      dockerfile: ../Dockerfile.frontend
      args:
        VITE_API_BASE: http://backend:8080
    ports:
      - "80:80"
    restart: always
    depends_on:
      - backend
    networks:
      - internal

networks:
  internal:
    driver: bridge
