version: "3.9"
services:
  backend:
    build:
      context: ./backend
    expose:
      - "8080"
    networks:
      - internal

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE: "http://backend:8080"
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - internal

networks:
  internal:
    driver: bridge
