FROM node:20 AS builder
WORKDIR /app

ARG VITE_API_BASE

COPY frontend/package*.json ./
RUN npm install
COPY frontend/ .

ENV VITE_API_BASE=$VITE_API_BASE
RUN npm run build

FROM nginx:1.27
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf

